patch:
  summary: Changes user's password
  security:
    - bearerAuth: []
  tags:
    - Account Settings
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            current_password:
              type: string
            new_password:
              type: string
            new_password_repeat:
              type: string
  responses:
    200:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
    401:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string