---
openapi: 3.0.0
info:
  description: Rafał Figlus
  version: 1.0.0
  title: YourTour REST API
  contact:
    email: figlusrafal@gmail.com
paths:
  # Authentication endpoints
  "/api/authentication/register":
      $ref: "./paths/register.yaml"

  "/api/authentication/login":
      $ref: "./paths/login.yaml"

  "/api/authentication/token/refresh":
    $ref: "./paths/token-refresh.yaml"


  # Tours endpoints
  "/api/tour/new_tour":
      $ref: "./paths/new-tour.yaml"

  "/api/tour/tour":
    $ref: "./paths/tour-details.yaml"

  "/api/tour/tours":
    get:
      tags:
        - Tour
      summary: Returns limited number of tour's data and information about total search results and number of pages


# Message endpoints
  "/api/messages/unicast/new":
      $ref: "./paths/message-unicast-new.yaml"

  "/api/messages/unicast/response":
      $ref: "./paths/message-unicast-response.yaml"

  "/api/messages/guide/offer/threads":
    $ref: "./paths/messages-guide-offer-threads.yaml"

  "/api/messages/thread/messages":
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - Messages
      summary: Returns limited amout of messages in thread
      parameters:
        - in: query
          name: thread_id
          required: true
          schema:
            type: integer
          description: ID of the thread fetched messges belong to
        - in: query
          name: offset
          required: true
          schema:
            type: integer
            default: 0
          description: Describes number of messages already loaded
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    content:
                      type: string
                    creation_date:
                      type: string
                    creation_time:
                      type: string
                    id:
                      type: integer
                    side:
                      type: string
                      description: left/right - defines side of messages display
                    was_read:
                      type: integer


  "/api/messages/threads/guide":

  "/api/messages/threads/user":



  "/api/guide/tours/active":
      $ref: "./paths/guide-active-tours.yaml"

  "/api/guide/tours/closed":
    get:
      tags:
        - Guide

  "/api/tour/tags":
    get:
      tags:
        - Tour
        #TODO: Continue

  "/api/tour/places":
    $ref: "./paths/places.yaml"





components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    TourDetails:
