---
openapi: 3.0.0
info:
  description: Rafał Figlus
  version: 1.0.0
  title: YourTour REST API
  contact:
    email: figlusrafal@gmail.com
paths:
  # Authentication endpoints
  "/api/authentication/register":
      $ref: "./paths/register.yaml"

  "/api/authentication/login":
      $ref: "./paths/login.yaml"

  "/api/authentication/token/refresh":
    $ref: "./paths/token-refresh.yaml"

  "/api/authentication/confirm":
    post:
      summary: Confirms registered account
      tags:
        - Authentication
      parameters:
        - in: query
          name: token
          schema:
            type: string
          required: true
          description: Unique confirmation token
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  payload:
                    type: object
        # Tours endpoints
  "/api/tour/new_tour":
      $ref: "./paths/new-tour.yaml"

  "/api/tour/tour":
    $ref: "./paths/tour-details.yaml"

  "/api/tour/tours":
    $ref: "./paths/tours.yaml"

  "/api/tour/offer":
    $ref: "./paths/tour-offer-modify.yaml"



  # Message endpoints
  "/api/messages/unicast/new":
      $ref: "./paths/message-unicast-new.yaml"

  "/api/messages/unicast/response":
      $ref: "./paths/message-unicast-response.yaml"

  "/api/messages/guide/offer/threads":
    $ref: "./paths/messages-guide-offer-threads.yaml"

  "/api/messages/thread/messages":
    $ref: "./paths/messages-thread-messages.yaml"

  "/api/messages/general/threads":
    $ref: "./paths/message-general-threads.yaml"


  "/api/messages/thread/delete":
    $ref: "./paths/messages-thread-delete.yaml"

  "/api/messages/thread/restore":
    $ref: "./paths/messages-thread-restore.yaml"

# Guide endpoints
  "/api/guide/tours/active":
      $ref: "./paths/guide-active-tours.yaml"

  "/api/guide/tours/closed":
    get:
      tags:
        - Guide

# Settings
  "/api/settings/password":
    $ref: "./paths/settings-password.yaml"

  "/api/settings/personal_data":
    $ref: "./paths/settings-personal-data.yaml"


        # Enrollments endpoints
  "/api/enrollments/enrollment":
    post:
      tags:
        - Enrollments
      summary: Creates new enrollment to given offer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                participants:
                  type: array
                  items:
                    type: string
                    example: "Joe Doe"
                f_name:
                  type: string
                  example: Rudy
                l_name:
                  type: string
                  example: Reyes
                phone_number:
                  type: integer
                  example: 696678260
                email:
                  type: string
                  example: rudyrr@gmail.com
                tour_id:
                  type: integer
                  example: 20
                city:
                  type: string
                  example: "Nowe Chechło"
                postcode:
                  type: string
                  example: "42-622"
                street:
                  type: string
                  example: "Lasowicka"
                house_number:
                  type: integer
                  example: 49
                apartment_number:
                  type: string
                  example: 2a
                comment:
                  type: string
                  example: Lorem ipsum sint occaecat cupidatat non proident, sunt in culpa qui officia.
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
    get:
      security:
        - bearerAuth: []
      tags:
        - Enrollments
      summary: Returns all enrollments connected with given tour ID
      parameters:
        - in: query
          name: tour_id
          schema:
            type: integer
            example: 30
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  f_name:
                    type: string
                  l_name:
                    type: string
                  email:
                    type: string
                  phone_number:
                    type: integer
                  tickets:
                    type: integer
                  participants:
                    type: array
                    items:
                      type: string
                  message_threads:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        topic:
                          type: string







                    # Endpoints for static information
  "/api/tour/tags":
    get:
      tags:
        - Tour
        #TODO: Continue
      responses:

  "/api/tour/places":
    $ref: "./paths/places.yaml"





components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    TourDetails:
