---
openapi: 3.0.0
info:
  description: Rafał Figlus
  version: 1.0.0
  title: YourTour REST API
  contact:
    email: figlusrafal@gmail.com
paths:
  # Authentication endpoints
  "/api/authentication/register":
      $ref: "./paths/register.yaml"

  "/api/authentication/login":
      $ref: "./paths/login.yaml"

  "/api/authentication/token/refresh":
    $ref: "./paths/token-refresh.yaml"


  # Tours endpoints
  "/api/tour/new_tour":
      $ref: "./paths/new-tour.yaml"

  "/api/tour/tour":
    $ref: "./paths/tour-details.yaml"

  "/api/tour/tours":
    get:
      tags:
        - Tour
      summary: Returns limited number of tour's data and information about total search results and number of pages


# Message endpoints
  "/api/messages/unicast/new":
      $ref: "./paths/message-unicast-new.yaml"

  "/api/messages/unicast/response":
      $ref: "./paths/message-unicast-response.yaml"

  "/api/messages/guide/offer/threads":
    $ref: "./paths/messages-guide-offer-threads.yaml"

  "/api/messages/thread/messages":
    $ref: "./paths/messages-thread-messages.yaml"

  "/api/messages/general/threads":
    $ref: "./paths/message-general-threads.yaml"

  "/api/messages/thread/delete":
    patch:
      security:
        - bearerAuth: []
      tags:
        - Messages
      summary: Deletes thread given by its ID on sender/receiver side
      description: Side of thread for which thread will be deleted is defined by access token identity
      requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  thread_id:
                    type: integer
                    example: 29
      responses:
        '201':
          description: Thread deleted
          content:
            application/json:
              schema:
                properties:
                  msg:
                    type: string
                    example: "Thread has been deleted"
        '422':
          description: Not enough data
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                  payload:
                    type: object


  "/api/messages/threads/guide":

  "/api/messages/threads/user":



  "/api/guide/tours/active":
      $ref: "./paths/guide-active-tours.yaml"

  "/api/guide/tours/closed":
    get:
      tags:
        - Guide

  "/api/tour/tags":
    get:
      tags:
        - Tour
        #TODO: Continue

  "/api/tour/places":
    $ref: "./paths/places.yaml"





components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    TourDetails:
