---
openapi: 3.0.0
info:
  description: Rafał Figlus
  version: 1.0.0
  title: YourTour REST API
  contact:
    email: figlusrafal@gmail.com
paths:
  # Authentication endpoints
  "/api/authentication/register":
      $ref: "./paths/register.yaml"

  "/api/authentication/login":
      $ref: "./paths/login.yaml"

  "/api/authentication/token/refresh":
    $ref: "./paths/token-refresh.yaml"

  "/api/authentication/confirm":
    post:
      summary: Confirms registered account
      tags:
        - Authentication
      parameters:
        - in: query
          name: token
          schema:
            type: string
          required: true
          description: Unique confirmation token
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  payload:
                    type: object
        # Tours endpoints
  "/api/tour/new_tour":
      $ref: "./paths/new-tour.yaml"

  "/api/tour/tour":
    $ref: "./paths/tour-details.yaml"

  "/api/tour/tours":
    $ref: "./paths/tours.yaml"

  "/api/tour/offer":
    $ref: "./paths/tour-offer-modify.yaml"


# User endpoints
  "/api/user/enrollments":
    get:
      tags:
        - User
      security:
        - bearerAuth: []
      summary: Get user's active enrollments
      parameters:
        - in: query
          name: user_id
          schema:
            type: integer
            example: 1
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  header:
                    type: string
                  guide_f_name:
                    type: string
                  guide_l_name:
                    type: string
                  start_date:
                    type: string
                  end_date:
                    type: string
                  payment_status:
                    type: string
                  tour_id:
                    type: integer
                  amount_paid:
                    type: integer
                  amount_payable:
                    type: integer
                  amount_remaining:
                    type: integer
        # Message endpoints
  "/api/messages/unicast/new":
      $ref: "./paths/message-unicast-new.yaml"

  "/api/messages/unicast/response":
      $ref: "./paths/message-unicast-response.yaml"

  "/api/messages/guide/offer/threads":
    $ref: "./paths/messages-guide-offer-threads.yaml"

  "/api/messages/thread/messages":
    $ref: "./paths/messages-thread-messages.yaml"

  "/api/messages/general/threads":
    $ref: "./paths/message-general-threads.yaml"


  "/api/messages/thread/delete":
    $ref: "./paths/messages-thread-delete.yaml"

  "/api/messages/thread/restore":
    $ref: "./paths/messages-thread-restore.yaml"

# Guide endpoints
  "/api/guide/tours/active":
      $ref: "./paths/guide-active-tours.yaml"

  "/api/guide/tours/closed":
    get:
      tags:
        - Guide

# Settings
  "/api/settings/password":
    $ref: "./paths/settings-password.yaml"

  "/api/settings/personal_data":
    $ref: "./paths/settings-personal-data.yaml"


  # Enrollments endpoints
  "/api/enrollments/enrollment":
    $ref: "./paths/enrollments-enrollment.yaml"

  # Payment endpoints
  "/api/payment/bitpay":
    post:

        # Endpoints for static information
  "/api/tour/tags":
    get:
      tags:
        - Tour
        #TODO: Continue
      responses:

  "/api/tour/places":
    $ref: "./paths/places.yaml"





components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    TourDetails:
