---
openapi: 3.0.0
info:
  description: Rafał Figlus
  version: 1.0.0
  title: YourTour REST API
  contact:
    email: figlusrafal@gmail.com
paths:
  # Authentication endpoints
  "/api/authentication/register":
      $ref: "./paths/register.yaml"

  "/api/authentication/login":
      $ref: "./paths/login.yaml"

  "/api/authentication/token/refresh":
    $ref: "./paths/token-refresh.yaml"


  # Tours endpoints
  "/api/tour/new_tour":
      $ref: "./paths/new-tour.yaml"

  "/api/tour/tour":
    $ref: "./paths/tour-details.yaml"

  "/api/tour/tours":
    get:
      tags:
        - Tour
      summary: Returns limited number of tour's data and information about total search results and number of pages


# Message endpoints
  "/api/messages/message/new":
    post:
      security:
        - bearerAuth: []
      tags:
        - Messages
      summary: Creates new message to one recipient
      description: New message to only one recipient - creates new message thread and first message in that thread
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tour_id:
                  type: integer
                  example: 1
                sender_id:
                  type: integer
                  example: 1
                receiver_id:
                  type: integer
                  example: 3
                topic:
                  type: string
                  example: Sit voluptatem accusantium doloremque.
                content:
                  type: string
                  example: Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string



  "/api/messages/message/response":
    post:
      security:
        - bearerAuth: []
      tags:
        - Messages
      summary: Creates response message to an existing thread
      description: Response message to existing thread - thread between two users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                thread_id:
                  type: integer
                  example: 1
                sender_id:
                  type: integer
                  example: 1
                receiver_id:
                  type: integer
                  example: 3
                content:
                  type: string
                  example: Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string

  "/api/guide/tours/active":
      $ref: "./paths/guide-active-tours.yaml"

  "/api/guide/tours/closed":
    get:
      tags:
        - Guide

  "/api/tour/tags":
    get:
      tags:
        - Tour
        #TODO: Continue

  "/api/tour/places":
    $ref: "./paths/places.yaml"





components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    TourDetails:
