import NavbarComponent from "../components/NavbarComponent";


function Informations(){
    return(
        <div className="informations">
            <NavbarComponent />
            Informations
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
            <p>
                asd
            </p>
        </div>
    )
}

export default Informations;