---
openapi: 3.0.0
info:
  description: Rafał Figlus
  version: 1.0.0
  title: YourTour REST API
  contact:
    email: figlusrafal@gmail.com
paths:
  # Authentication endpoints
  "/authentication/register":
    post:
      tags:
        - Authentication
        #TODO: Continue
  "/authentication/login":
    post:
      tags:
        - Authentication
        #TODO: Continue
  "/authentication/logout":
    post:
       tags:
        - Authentication
        #TODO: Continue

  # Tours endpoints
  "/tour/new_tour":
    post:
      tags:
        - Tour
      summary: Creates new tour
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/NewTour"

      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: "Done"
        '422':
          description: Not enough data
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: "Could not process data"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: "Server error, try again"









  "/tour/tours":
    get:
      tags:
        - Tour
      summary: Returns limited number of tour's data and information about total search results and number of pages


  "/tour/tour":
    get:
      tags:
        - Tour
      summary: Returns all informations about tour specified by its ID
      parameters:
        - in: query
          name: tour_id
          schema:
            type: integer
            example: 310
          required: true
          description: ID of tour which information will be returned
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TourDetails"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: Pożądana oferta nie została znaleziona


  "/tour/tags":
    get:
      tags:
        - Tour
        #TODO: Continue
  "/tour/places":
    get:
      tags:
        - Tour
      summary: Returns array of objects with cities/towns in Poland
      description: >
        All cities and town in Poland are stored in the database. While creating new tour guide can select proper cities for his tour. Array of objects is returned
        based on input sent in query. Number of returned items is limited.
      parameters:
        - in: query
          name: place
          schema:
            type: string
            example: "Tarnowskie Gó"
          required: true
          description: User input, may be incomplete
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    place:
                      type: string

  "/tour/tour_places":
    get:
      tags:
        - Tour
        #TODO: Continue
  "/tour/tour_tags":
    get:
      tags:
        - Tour
        #TODO: Continue






components:
  schemas:
    NewTour:
      type: object
      properties:
        tour_data:
          type: object
          properties:
            guide_id:
              type: integer
            header:
              type: string
            description:
              type: string
            person_limit:
              type: integer
            price:
              type: integer
            start_date:
              type: string
            end_date:
              type: string
            tour_plan:
              type: array
              items:
                type: string
            tour_places:
              type: array
              items:
                type: integer
        electives:
          type: object
          properties:
            imageGallery:
              type: boolean
            importantInfo:
              type: boolean
            priceList:
              type: boolean
        price_list:
          type: array
          items:
            type: object
            properties:
              text:
                type: string
              variant:
                type: boolean
        important_info:
          type: array
          items:
            type: string
        main_image:
          type: string
          format: binary
        images:
          type: array
          items:
            type: string
            format: binary
      required:
        - tour_data
        - electives
        - main_image
    TourDetails:
      type: object
      properties:
        general_data:
          type: object
          properties:
            header:
              type: string
              example: "Header of the tour"
            description:
              type: string
              example: "Description of the tour. Very well described."
            start_date:
              type: string
              example: "2021/07/01"
            end_date:
              type: string
              example: "2021/08/30"
            price:
              type: integer
              example: 150
            person_limit:
              type: integer
              example: 25
            guide_id:
              type: integer
              example: 1
        guide_data:
          type: object
          properties:
            f_name:
              type: string
              example: "Joe"
            l_name:
              type: string
              example: "Black"
            id:
              type: integer
              example: 1
            email:
              type: string
              example: "joeblackk@gmail.com"
            phone_number:
              type: integer
              example: 956567393
        tour_plan:
          type: array
          items:
            type: object
            properties:
              description:
                type: string
                example: "Description of the tour plan point"
              number:
                type: integer
                example: 1
                summary: Defines the order of the plan points

